services:

  cassandra:
    image: cassandra:3.11
    container_name: cassandra
    environment:
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=128M
    ports:
      - "9042:9042"

  thehive:
    image: strangebee/thehive:4
    container_name: thehive
    depends_on:
      - cassandra
    environment:
      - JVM_OPTS=-Xms512m -Xmx512m
    ports:
      - "9000:9000"