version: '3'
services:
  cassandra:
    image: cassandra:3.11
    container_name: cassandra
    environment:
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=128M
    ports:
      - "9042:9042"
    volumes:
      - cassandra_data:/var/lib/cassandra

  thehive:
    image: strangebee/thehive:4.0.4
    container_name: thehive
    depends_on:
      - cassandra
    environment:
      - JVM_OPTS=-Xms100m -Xmx512m
    ports:
      - "9000:9000"

volumes:
  cassandra_data: